### ISSUE TITLE
WinError 3] 系统找不到指定的路径。: 'checkpoints'

### ISSUE THREAD

**Issue by renhaofan** [CaptainEven/Face-recognition-#2]
I try python main.py
there is a error:
Traceback (most recent call last):
  File "main.py", line 290, in <module>
    test_triplet()
  File "main.py", line 55, in test_triplet
    checkpoints = os.listdir(args.check_path)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'checkpoints'
how to solve it ?

**Comment by liuyang151617** [comment]
please ensure that you have downloaded the 'epoch_45.pth' which is mentioned in Readme. Maybe you forgot it, just like me ^^
